FROM bitnami/spark:3.2.1

WORKDIR /opt

# Adiciona arquivos ao container
COPY scripts/spark_job.py .
COPY .env .

# Instala pacote para ler variáveis de ambiente
RUN pip install python-dotenv

# Executa o script PySpark
CMD [ "/opt/bitnami/spark/bin/spark-submit", "spark_job.py" ]
